#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=4:00:00,mem=10gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

module load FastQC/0.11.5

cd ${PBS_O_WORKDIR} || exit


cd RawReads || exit

gunzip -c CrX1_GCCAAT_L001_R1_001.fastq.gz > CrX1_GCCAAT_L001_R1_001.fastq
gunzip -c CrX1_GCCAAT_L001_R2_001.fastq.gz > CrX1_GCCAAT_L001_R2_001.fastq

cd ../QualityControl/raw || exit


fastqc ../../RawReads/CrX1_GCCAAT_L001_R1_001.fastq
fastqc ../../RawReads/CrX1_GCCAAT_L001_R2_001.fastq

cd ../../ || exit

qsub effective-octo-fortnight/1.2_Trim_Lichen.qsub
