#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=10,walltime=4:00:00,mem=10gb
#PBS -m a

cd ${PBS_O_WORKDIR} || exit

module load bowtie2/2.2.6

cd ../PublicData/PhiX/ || exit

bowtie2-build PhiX.fasta PhiX #build index

cd ${PBS_O_WORKDIR} || exit

bowtie2 -x ../PublicData/PhiX/PhiX \
-1 Cr_P_1.fastq -2 Cr_P_2.fastq -U Cr_U_1.fastq,Cr_U_2.fastq -S PhiXhits.sam -q \
--fast --un UnpairCr --un-conc PairCR -p10

qsub ../effective-octo-fortnight/3_Abyss_Lichen.qsub -N abyss_lichen_75 -v kmer=75
