#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=10,walltime=4:00:00,mem=10gb
#PBS -m a

cd ${PBS_O_WORKDIR} || exit

module load bowtie2/2.2.6

bowtie2-build ../../PublicData/PhiX/PhiX.fasta PhiX #build index

bowtie2 -x ../../PublicData/PhiX/PhiX ../../PublicData/PhiX/PhiX.fasta \
-1 Cr_P_1.fastq -2 Cr_P_2.fastq -U Cr_U_1.fastq,Cr_U_2.fastq -S PhiXhits.sam -q\
--fast --un UnpairCr --un-conc PairCR -p10
