#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=4:00:00,mem=10gb
#PBS -m abe

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

cd ${PBS_O_WORKDIR} || exit

module load Trimmomatic/0.33

java -jar $TRIM/trimmomatic PE -threads 7 -trimlog lichenTrim.log CrX1_GCCAAT_L001_R1_001.fastq CrX1_GCCAAT_L001_R1_001.fastq
CrX_F_P.fq CrX_F_U.fq CrX_R_P.fq
CrX_R_U.fq ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3
TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:51