#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=4:00:00,mem=10gb
#PBS -m abe
#PBS -N abyss_lichen_${kmer}

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

cd ${PBS_O_WORKDIR}


mkdir k${kmer}


module load ABySS/1.9.0

    abyss-pe k=${kmer} -C k${kmer} name=${PBS_JOBID} in='../Cr_P_1.fastq  ../Cr_P_2.fastq' se='../Cr_U_1.fastq  ../Cr_U_2.fastq'
    
if [ "${kmer}" -le "63" ]; then
	newkmer=$[${kmer} +1]
	#echo $newkmer
	qsub ../effective-octo-fortnight/3_Abyss_Lichen.qsub -v kmer="${newkmer}"
fi
