#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=4:00:00,mem=10gb
#PBS -m abe


# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

cd ${PBS_O_WORKDIR}


mkdir k${kmer}


module load SPAdes/3.7.1

    spades.py -1 ../Cr_P_1.fastq -2 ../Cr_P_2.fastq --pe<1>-s ../Cr_U_1.fastq --pe<2>-s ../Cr_U_2.fastq -o k${kmer}
        
if [ "${kmer}" -le "71" ]; then
	newkmer=$[${kmer} + 2]
	#echo $newkmer
	qsub ../4_SPADES_Lichen -N "SPADES_lichen_${newkmer}" -v kmer="${newkmer}"
fi
