#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=30:00:00,mem=100gb
#PBS -m abe


# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

cd ${PBS_O_WORKDIR}


module load HMMER/3.1b2
module load SPAdes/3.7.1
    ~/SoftwareFiles/SPAdes-3.9.0-Linux/bin/spades.py -t 8 -m 20 -1 ../../RawReads/CrX1_GCCAAT_L001_R1_001.fastq -2 ../../RawReads/CrX1_GCCAAT_L001_R2_001.fastq -o RawSPADES
        
